### ISSUE TITLE
Documentation of Missing Features. 

### ISSUE THREAD

**Issue by zephraph** [neumino/reqlite#3]
I'm going to go ahead and start a list of features I find that are missing from reql. This will be updated as we go. Please let me know if I missed anything!

## Stream
_Not Implemented_

## r (rethink object, may not be desired)
- [ ] dbCreate
- [ ] dbDrop
- [ ] dbList

## Database
- [ ] tableList

## Table
- [ ] indexList
- [ ] indexRename
- [ ] indexStatus
- [ ] changes
- [ ] update
- [ ] replace
- [ ] delete (_Note: Exists, but is currently _delete_)
- [ ] sync

## Sequence
- [ ] innerJoin (_Note: It looks like both of these functions are implemented in a single ```join``` method_)
- [ ] outerJoin
- [ ] offsetsOf
- [ ] union (?)

**Comment by neumino** [comment]
Thanks for putting that up @zephraph.

So I have recently started to work again on reqlite. I'm sorting out a few things first. but I should be clear to push in 2-3 weeks. I don't remember all the details, but I can provide a list of things that are currently not available in my branch

**Stuff that I should be able to finish for next release**
- [ ] geospatial operation -- baring rounding errors
- [ ] changefeeds -- That's requires some plumbing
- [ ] Syncing to disk -- I would actually use it for stuff like `rethinkdbdash`/`thinky`
- [ ] Fake system tables

** Things I would like to do**
- [ ] Use a B-trees instead of a hash table to index documents -- That would actually help a bit for lazily evaluating streams.
- [ ] Actually build B-trees for secondary indexes

** Things I'm not sure**
- [ ] `r.js` with a lambda function -- I have a simple `r.js` command, 
- [ ] `r.http` because it is the only asynchronous operation and is a pain-ish to do.

** Things I don't plan to do** (but I would merge a PR if someone does it)
- [ ] Real clustering operations -- I don't plan to implement them for now as you can't cluster reqlite
- [ ] Lazily evaluating streams
- [ ] `r.range()` followed by a method that keep the stream type -- because it would require a decent chunk of work/refactoring and is kind of out of the scope of reqlite for now.

As far as I know, all the rest work. There might be a few assertions missing for types, but that's all. The test framwork was reworked a bit. The test are basically now running queries against reqlite and rethinkdb and compare the output.

**Comment by zephraph** [comment]
/cc @Slava 

I'm really wanting to see baked in support for rethinkdb in meteor so I'll do everything that I can to facilitate this library. Feel free to assign me tasks if you would like me to investigate or work on certain tasks.

**Comment by Slava** [comment]
I think we need more tests on the queries. At this point I am not even sure if basic operations like "add" and "orderBy" work w/o bugs. Fixing the existing tests would be a good start. Also, @neumino, are there tests we can adopt from the main rethinkdb repo?

**Comment by neumino** [comment]
@Slava -- Yes, for now I wrote the queries myself to make sure that all the code paths were tested.
I plan to just pull all the tests for the JS driver and dump it in reqlite.

**Comment by neumino** [comment]
Opened a lot of issues to track done what's left. Closing this meta issue.

**Comment by neumino** [comment]
@Slava -- Could you check that _saveOriginal still works for your need? It was a big merge ;-)

**Comment by neumino** [comment]
@zephraph -- if you want to help now, there are tons of things to grab.

**Comment by zephraph** [comment]
I see that, haha. I'll look through the open tasks.
